version: "3"
services:
  clipboard-nodeserver:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: clipboard-nodeserver
    ports:
      - "8000:8000"
    networks:
      - clipboard-app
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.9
    ports:
      - "27017:27017"
    networks:
      - clipboard-app
    volumes:
      - mongo-data:/data/db
  mongoui:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - clipboard-app
    ports:
      - "28081:8081"
networks:
  clipboard-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
